name: Build & Test
on:
  push:
    branches:
      - "**"
env:
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run build
      - name: Link Binary & Test
        # Temporary running only unit tests in ci.
        run: pnpm i && pnpm run --filter=./cli test:ci
      - name: Coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./cli/coverage/lcov.info
          github-token: ${{ github.token }}
