name: Static Analyses
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run fmt

  test_basic:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
        - uses: actions/checkout@v4
        - uses: pnpm/action-setup@v3
          with:
            version: 8
        - uses: actions/setup-node@v4
          with:
            node-version: 20.11.1
            cache: "pnpm"
        - run: pnpm install
        - run: pnpm test
  